### ISSUE TITLE
Fatal error при неправильных конфигах mysql

### ISSUE THREAD

**Issue by dani32iz** [alpharder/learn-ecommerce#1]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /Users/daniil/Sites/learn-ecommerce/db.php:14 Stack trace: #0 /Users/daniil/Sites/learn-ecommerce/db.php(14): PDO->__construct('mysql:host=127....', 'root', 'root') #1 /Users/daniil/Sites/learn-ecommerce/db.php(37): get_connection() #2 /Users/daniil/Sites/learn-ecommerce/functions.php(45): db_select('SELECT id, pric...') #3 /Users/daniil/Sites/learn-ecommerce/layouts/header.php(9): get_cart_data() #4 /Users/daniil/Sites/learn-ecommerce/functions.php(27): require_once('/Users/daniil/S...') #5 /Users/daniil/Sites/learn-ecommerce/controllers/homepage.php(9): display_template('homepage', Array) #6 /Users/daniil/Sites/learn-ecommerce/index.php(50): require_once('/Users/daniil/S...') #7 {main} thrown in /Users/daniil/Sites/learn-ecommerce/db.php on line 14

**Comment by alpharder** [comment]
А ты хочешь чтобы по экрану пробегала пони при неправильных конфигах? 
Такими темпами скоро ты запостишь карточку "Нет интеграции с пейпал"

**Comment by dani32iz** [comment]
Хочу "проблемы с базой"

**Comment by alpharder** [comment]
@dani32iz "проблемы с базой" - очень информативно. куда более информативно чем exception с полным описанием проблемы. ты не путай - эта система не для пользователей а для разработчиков чтобы понимали как вообще магазин и CMS внутри работает, общие принципы

**Comment by dani32iz** [comment]
Я показывал одному из твоих разработчиков, что "архив в вконтактике" плохой способ передачи кода, показал как постить баги в гитхабе и делать пулл реквесты.

Странно, что ты этого не показал :)

Я понимаю, что постингом багов, я задел тебя за живое, смел усомниться в неприкасаемости твоего прекрасного кода.

**Comment by dani32iz** [comment]
Вообще не дело оставлять в репозитории нерабочий код.

**Comment by alpharder** [comment]
@dani32iz ты делал то что ты должен делать в рамках своего курса. если я буду на базовом PHP рассказывать про GIT, то я им не успею рассказать про куки и сессии. 

> Вообще не дело оставлять в репозитории нерабочий код.
Репозиторий предназначается для слушателей курса, которые знают что где и как настроить в своей базе.

**Comment by dani32iz** [comment]
1. Показать и использовать правильную культуру не займёт много времени, точнее вообще не займёт, просто делаешь и всё :)
2. Это ты мне дал ссылку на репозиторий :) со словами идеальная CMS

**Comment by dani32iz** [comment]
Я не знал, что ты так болезненно относишься к комментариям и рекомендациям.

**Comment by alpharder** [comment]
> Я понимаю, что постингом багов, я задел тебя за живое, смел усомниться в неприкасаемости твоего прекрасного кода.

Угу, у меня есть зависимость от твоего мнения и я не воспринимаю критику. Неадекватную и претенциозную со смайликами.

:)

Только вот непонятно в чём баг - ты как-то быстро перешёл от "хочу проблемы с базой" (эксепшен-то поинформативнее будет) к "архив вконтакте - говно" и "хули ты не рассказал им про git".

> Показать и использовать правильную культуру не займёт много времени, точнее вообще не займёт, просто делаешь и всё :)

Я их учу писать код, а не инфраструктуре разработки. Это ещё одна большая сфера и по одному гиту можно отдельный курс запустить - если у тебя есть на курсе возможность рассуждать об эфемерных "методах решения возникающих проблем" и попутно от нечего делать рассказать про GIT, то у меня к сожалению слишком много инфы есть которую надо им надо рассказать показать и объяснить.

> Это ты мне дал ссылку на репозиторий :) со словами идеальная CMS

"Зацените интернет магазин на чистом пхп сбацал https://github.com/alpharder/learn-ecommerce" 

really?

> Я не знал, что ты так болезненно относишься к комментариям и рекомендациям.

Ты привык что твои подчинённые не имеют собственных мнений и несогласные мнения это "болезненное восприятие"?)

**Comment by dani32iz** [comment]
Что значит "непонятно в чём баг?"

1. Параметры базы используются в разных файлах (index.php и installer.php) , в этой ситуации нужно делать конфиг 100% 
2. Баг с отсутствием товаров в корзине, который не был пофикшен на момент тестирования, который и вызывал Fatal error при старте. 

Что приводит к пониманию, что ты выдал сырой и нерабочий код, не рассчитывал что его кто то будет запускать. 

А отмазки → это всё для курса и для другого → это отмазки.

**Comment by alpharder** [comment]
2. какого тестирования? ты о чём, друг? зачем ты вообще его запустил-то не сходив на курс?

**Comment by dani32iz** [comment]
Ага, тоесть ты опубликовал ссылку на свой репозиторий, чтобы кто то просто посмотрел прекрасный код и не запускал его? 

Я вот запустил и увидел ошибки :) Сделай README

**Comment by alpharder** [comment]
> А отмазки → это всё для курса и для другого → это отмазки.

Вторник. Вечер. Офис Симтек. Я вскользь упомянул: "Завтра бутерброд с утра наверное поем".
Среда. Утро. Сижу, значит, у себя дома на кухне в трусах, кушаю бутерброд.
Забегает Данила, откусывает кусок и вопит: "Несолёное!!! НЕсолёное!! Говно! Говно"

- "Даня, но я же..."
- "Говно!"
- "Я же себе сделал..."
- "Ещё и микроволновка грязная! Говно, пидоры блядь!"
- "Но я не ем соль.."
- "Говно! Говно! Отмазки!"
- "Блядь..."

**Comment by alpharder** [comment]
Воскл. знак можно на смайлик ":)" заменить тогда ещё реалистичнее)

**Comment by alpharder** [comment]
> Ага, тоесть ты опубликовал ссылку на свой репозиторий, чтобы кто то просто посмотрел прекрасный код и не запускал его

Ты сказал что будешь жрать бутик чтобы все просто пожелали приятного аппетита?

**Comment by dani32iz** [comment]
Пилять, я тебе тупо багу запостил, а ты:

> А ты хочешь чтобы по экрану пробегала пони при неправильных конфигах? 
> Такими темпами скоро ты запостишь карточку "Нет интеграции с пейпал"

Что ты от меня ожидаешь при таком ответе?

Бросай бухать :)

**Comment by alpharder** [comment]
![Напомнило](http://s.pikabu.ru/images/big_size_comm/2013-12_4/13872652202168.gif)

**Comment by alpharder** [comment]
> Что ты от меня ожидаешь при таком ответе?

Ожидаю чтобы ты понял что эксепшн должен выбрасываться.
Творческий замысел.
"Я кодер я так вижу"

**Comment by dani32iz** [comment]
Хуйня, хуйня, всё хуйня

**Comment by alpharder** [comment]
пости ещё баги только keep in mind что это для обучения разработчиков а не для продажи клиенатам

**Comment by dani32iz** [comment]
Я покупателя нашёл, а тут такое, конечно я огорчён и взволнован.
